/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('job_posting').del();

  // Inserts seed entries
  await knex('job_posting').insert([
    {
      company_name: 'TechCorp Inc',
      location: 'New York, USA',
      degree: 'B.Tech',
      branch: 'Computer Science',
      employeer_name: 'John Doe',
      number_positions: 5,
      job_role: 'Software Developer',
      job_description: 'Develop and maintain web applications.',
      required_skills: 'JavaScript, React, Node.js',
      employement_type: 'Full_time',
      salary: '120000 USD',
      join_before: '2024-12-31',
      expiry: '2024-11-30 23:59:59',
    },
    {
      company_name: 'Innova Solutions',
      location: 'San Francisco, USA',
      degree: 'M.Tech',
      branch: 'Electronics',
      employeer_name: 'Jane Smith',
      number_positions: 3,
      job_role: 'Hardware Engineer',
      job_description: 'Design and test hardware systems.',
      required_skills: 'VHDL, Verilog, MATLAB',
      employement_type: 'Full_time',
      salary: '90000 USD',
      join_before: '2024-11-15',
      expiry: '2024-11-10 23:59:59',
    },
    {
      company_name: 'EduTech Solutions',
      location: 'London, UK',
      degree: 'B.Sc',
      branch: 'Information Technology',
      employeer_name: 'Emma Brown',
      number_positions: 10,
      job_role: 'UI/UX Designer',
      job_description: 'Design user interfaces and improve user experience.',
      required_skills: 'Figma, Adobe XD, HTML, CSS',
      employement_type: 'Internship',
      salary: '500 GBP/month',
      join_before: '2024-10-31',
      expiry: '2024-10-25 23:59:59',
    },
    {
      company_name: 'PixelSoft Solutions',
      location: 'Berlin, Germany',
      degree: 'M.Sc',
      branch: 'Data Science',
      employeer_name: 'Carlos Santos',
      number_positions: 2,
      job_role: 'Data Scientist',
      job_description: 'Analyze and process large datasets to generate insights.',
      required_skills: 'Python, SQL, Machine Learning',
      employement_type: 'Full_time',
      salary: '70000 EUR',
      join_before: '2024-12-15',
      expiry: '2024-12-01 23:59:59',
    },
    {
      company_name: 'CodeWorks Ltd.',
      location: 'Sydney, Australia',
      degree: 'MBA',
      branch: 'Business Administration',
      employeer_name: 'Ava Wilson',
      number_positions: 4,
      job_role: 'Business Analyst',
      job_description: 'Work with teams to improve business processes.',
      required_skills: 'Tableau, Excel, Communication',
      employement_type: 'Full_time',
      salary: '80000 AUD',
      join_before: '2024-11-30',
      expiry: '2024-11-20 23:59:59',
    },
    {
      company_name: 'CloudTech Innovations',
      location: 'Mumbai, India',
      degree: 'B.Tech',
      branch: 'Information Technology',
      employeer_name: 'Ravi Patel',
      number_positions: 6,
      job_role: 'Cloud Engineer',
      job_description: 'Build and manage cloud infrastructure.',
      required_skills: 'AWS, Azure, Linux',
      employement_type: 'Full_time',
      salary: '15,00,000 INR',
      join_before: '2024-10-31',
      expiry: '2024-10-20 23:59:59',
    },
    {
      company_name: 'FutureGen Labs',
      location: 'Tokyo, Japan',
      degree: 'B.E.',
      branch: 'Mechanical Engineering',
      employeer_name: 'Hiroshi Tanaka',
      number_positions: 3,
      job_role: 'Mechanical Engineer',
      job_description: 'Design and prototype mechanical systems.',
      required_skills: 'AutoCAD, SolidWorks, MATLAB',
      employement_type: 'Internship',
      salary: '200000 JPY/month',
      join_before: '2024-12-20',
      expiry: '2024-12-15 23:59:59',
    },
    {
      company_name: 'BrightTech Co.',
      location: 'Toronto, Canada',
      degree: 'B.Tech',
      branch: 'Electrical Engineering',
      employeer_name: 'Samantha Green',
      number_positions: 5,
      job_role: 'Electrical Engineer',
      job_description: 'Develop and maintain electrical systems.',
      required_skills: 'Power Systems, Embedded Systems, MATLAB',
      employement_type: 'Full_time',
      salary: '90000 CAD',
      join_before: '2024-11-15',
      expiry: '2024-11-10 23:59:59',
    },
    {
      company_name: 'Innovate AI Labs',
      location: 'Palo Alto, USA',
      degree: 'M.Tech',
      branch: 'Artificial Intelligence',
      employeer_name: 'Daniel Kim',
      number_positions: 8,
      job_role: 'AI Researcher',
      job_description: 'Conduct research in artificial intelligence.',
      required_skills: 'TensorFlow, Python, Deep Learning',
      employement_type: 'Full_time',
      salary: '150000 USD',
      join_before: '2024-12-01',
      expiry: '2024-11-25 23:59:59',
    },
    {
      company_name: 'EcoBuild Systems',
      location: 'Berlin, Germany',
      degree: 'M.Sc',
      branch: 'Civil Engineering',
      employeer_name: 'Fiona Muller',
      number_positions: 2,
      job_role: 'Civil Engineer',
      job_description: 'Design sustainable building solutions.',
      required_skills: 'Revit, AutoCAD, Structural Analysis',
      employement_type: 'Full_time',
      salary: '70000 EUR',
      join_before: '2024-11-30',
      expiry: '2024-11-15 23:59:59',
    },
    {
      company_name: 'SecureSoft Solutions',
      location: 'Austin, USA',
      degree: 'B.Sc',
      branch: 'Cybersecurity',
      employeer_name: 'Linda Thompson',
      number_positions: 7,
      job_role: 'Cybersecurity Analyst',
      job_description: 'Protect systems from cyber threats.',
      required_skills: 'Networking, Ethical Hacking, Python',
      employement_type: 'Full_time',
      salary: '95000 USD',
      join_before: '2024-11-01',
      expiry: '2024-10-25 23:59:59',
    },
    {
      company_name: 'DataWorks Inc.',
      location: 'Seattle, USA',
      degree: 'B.Sc',
      branch: 'Data Analytics',
      employeer_name: 'George Brown',
      number_positions: 4,
      job_role: 'Data Analyst',
      job_description: 'Analyze and visualize data.',
      required_skills: 'Power BI, SQL, Python',
      employement_type: 'Internship',
      salary: '3000 USD/month',
      join_before: '2024-10-31',
      expiry: '2024-10-25 23:59:59',
    },
  
  ]);
};
